<?xml version="1.0" encoding="UTF-8"?>
<project name="psalm" default="psalm:check">

  <target name="psalm:check" description="Check code with Psalm">
    <exec executable="vendor/bin/psalm" checkreturn="true" passthru="true">
      <arg line="--no-cache --long-progress"/>
    </exec>
  </target>

</project>
